name: frontend pull request workflow
# フロントエンドディレクトリに変更があるPRが作成された際に実行

on:
  pull_request:
    paths:
      - frontend/**

jobs:
  style_check:
    uses: ./.github/workflows/frontend_style_check.yml
  generate_check:
    uses: ./.github/workflows/frontend_build_check.yml
